### ISSUE TITLE
Add repo to awesome-esp-rust

### ISSUE THREAD

**Issue by SergioGasquez** [sambenko/esp32s3-box-examples#8]
Hi @sambenko!

Could you add this repo to https://github.com/esp-rs/awesome-esp-rust once its finished or in a good state?

**Comment by sambenko** [comment]
Hey @SergioGasquez 

after a longer hiatus, I'm back and gonna get to it asap.

**Comment by SergioGasquez** [comment]
Thanks for adding it!
